version: '3.8'
services:
  react-ui:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - './:/app'
      - '/app/node_modules'
    command: npm start